eval(File.read(File.dirname(__FILE__) + '/../common_dependencies.rb'))

gem 'guara_core', :path => "../../guara/core"
gem 'guara_crm', :path => "../../guara/crm"

gem 'gedi', :path => "../core/"
gem 'gedi_analysis', :path => "../analysis/"
gemspec
